---
all:
  vars:
    ansible_user: arai
    ansible_ssh_private_key_file: /Users/arai/.ssh/google_compute_engine

  children:
    app:
      hosts:
        app01:
          ansible_host: 34.84.152.110
    db:
      hosts:
        db01:
          ansible_host: 35.243.93.70
    monitor:
      hosts:
        monitor01:
          ansible_host: 34.104.208.223

